import Head from 'next/head'
import { Inter } from '@next/font/google'
import Landing from './Landing'
import { useUser } from '@auth0/nextjs-auth0/client';



const inter = Inter({ subsets: ['latin'] })

export default function Loan() {
  const { user } = useUser();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
      
      </>
  )
}
